apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lambda-devops
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lambda-devops
    spec:
      containers:
      - name: master
        image: gcr.io/blissful-acumen-179906/lambda-devops:v1.1
        ports:
          - containerPort: 8080
